/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aiks_util_RSAUtils */

#ifndef _Included_com_aiks_util_RSAUtils
#define _Included_com_aiks_util_RSAUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aiks_util_RSAUtils
 * Method:    encryptJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aiks_util_RSAUtils_encryptJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_aiks_util_RSAUtils
 * Method:    decryptJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aiks_util_RSAUtils_decryptJNI
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_aiks_util_RSAUtils
 * Method:    encryptJNIPri
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aiks_util_RSAUtils_encryptJNIPri
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_aiks_util_RSAUtils
 * Method:    decryptJNIPub
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aiks_util_RSAUtils_decryptJNIPub
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
